---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/vsphere-cpi-release}

inputs:
  - name: bosh-cpi-src
  - name: bosh-cpi-artifacts
  - name: release-version-semver

outputs:
  - name: updated-repo
  - name: integer-version

run:
  path: bosh-cpi-src/ci/tasks/promote-candidate.sh

params:
  AWS_ACCESS_KEY_ID:     ""
  AWS_SECRET_ACCESS_KEY: ""
