---
platform: linux
image: docker:///boshcpi/vsphere-cpi-release

inputs:
  - name: bosh-cpi-src
  - name: bosh-cpi-artifacts
  - name: release-version-semver

outputs:
  - name: updated-repo
  - name: integer-version

run:
  path: bosh-cpi-src/ci/tasks/promote-candidate.sh

params:
  aws_access_key_id:     replace-me
  aws_secret_access_key: replace-me
