---
platform: linux
image: docker:///boshcpi/vsphere-cpi-release
inputs:
  - name: bosh-cpi-release
  - name: stemcell
  - name: bats
  - name: vsphere-5.1-environment
run:
  path: bosh-cpi-release/ci/tasks/run-bats.sh
tags: ["vsphere-v5.1"]
params:
  base_os:                                         replace-me
  network_type_to_test:                            replace-me
  BAT_STEMCELL_NAME:                               replace-me
  BAT_VLAN:                                        replace-me
  BAT_VCAP_PASSWORD:                               replace-me
  BAT_SECOND_NETWORK_VLAN:                         replace-me
