---
groups:
  - name: bosh-vsphere-cpi-release
    jobs:
      - cache-stemcells
      - build-candidate
      - lifecycle-5.1
      - lifecycle-6.0
      - lifecycle-6.0-vsan
      - promote-candidate

  - name: vsphere-5.1
    jobs:
      - build-candidate
      - lifecycle-5.1
      - promote-candidate

  - name: vsphere-6.0
    jobs:
      - build-candidate
      - lifecycle-6.0
      - lifecycle-6.0-vsan
      - promote-candidate

jobs:
  - name: cache-stemcells
    plan:
      - aggregate:
        - {trigger: true, get: vsphere-centos-stemcell, tags: ["vsphere-v5.1"]}
        - {trigger: true, get: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}

      - task: setup-container
        tags: ["vsphere-v5.1"]
        config:
          platform: linux
          image: docker:///boshcpi/vsphere-cpi-release
          inputs:
            - name: vsphere-centos-stemcell
            - name: vsphere-ubuntu-stemcell
          run:
            path: echo
            args: ["Finished setting up container."]

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false, get: version-semver, params: {bump: patch}, tags: ["vsphere-v5.1"]}

      - put: version-semver
        tags: ["vsphere-v5.1"]
        params: {file: version-semver/number}

      - task: build
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/build-candidate.yml

      - put: bosh-cpi-artifacts
        tags: ["vsphere-v5.1"]
        params: {from: dev-artifacts/.*\.tgz}

  - name: lifecycle-5.1
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}

      - task: test
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          BOSH_VSPHERE_VERSION:                                 {{lifecycle_vsphere_5_1_version}}
          BOSH_VSPHERE_CPI_HOST:                                {{lifecycle_vsphere_5_1_host}}
          BOSH_VSPHERE_CPI_USER:                                {{lifecycle_vsphere_5_1_user}}
          BOSH_VSPHERE_CPI_PASSWORD:                            {{lifecycle_vsphere_5_1_password}}
          BOSH_VSPHERE_VLAN:                                    {{lifecycle_vsphere_5_1_vlan}}
          BOSH_VSPHERE_CPI_DATACENTER:                          {{lifecycle_vsphere_5_1_datacenter}}
          BOSH_VSPHERE_CPI_CLUSTER:                             {{lifecycle_vsphere_5_1_first_cluster}}
          BOSH_VSPHERE_CPI_DATASTORE_PATTERN:                   {{lifecycle_vsphere_5_1_datastore_pattern_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_PERSISTENT_DATASTORE_PATTERN:        {{lifecycle_vsphere_5_1_persistent_datastore_pattern_available_to_all_clusters}}
          BOSH_VSPHERE_CPI_SECOND_DATASTORE:                    {{lifecycle_vsphere_5_1_second_datastore_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_LOCAL_DATASTORE_PATTERN:             {{lifecycle_vsphere_5_1_local_datastore_pattern_available_to_a_single_host_in_first_cluster}}
          BOSH_VSPHERE_CPI_RESOURCE_POOL:                       {{lifecycle_vsphere_5_1_first_cluster_first_resource_pool}}
          BOSH_VSPHERE_CPI_SECOND_RESOURCE_POOL:                {{lifecycle_vsphere_5_1_first_cluster_second_resource_pool}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER:                      {{lifecycle_vsphere_5_1_second_cluster}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_DATASTORE:            {{lifecycle_vsphere_5_1_datastore_pattern_available_to_all_hosts_in_second_cluster}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_RESOURCE_POOL:        {{lifecycle_vsphere_5_1_second_cluster_first_resource_pool}}
          BOSH_VSPHERE_CPI_VM_FOLDER:                           {{lifecycle_vsphere_5_1_vm_folder}}
          BOSH_VSPHERE_CPI_TEMPLATE_FOLDER:                     {{lifecycle_vsphere_5_1_template_folder}}
          BOSH_VSPHERE_CPI_DISK_PATH:                           {{lifecycle_vsphere_5_1_disk_path}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER:                   {{lifecycle_vsphere_5_1_nested_datacenter}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_DATASTORE_PATTERN: {{lifecycle_vsphere_5_1_nested_datacenter_datastore_pattern}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_CLUSTER:           {{lifecycle_vsphere_5_1_nested_datacenter_cluster}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_RESOURCE_POOL:     {{lifecycle_vsphere_5_1_nested_datacenter_resource_pool}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_VLAN:              {{lifecycle_vsphere_5_1_nested_datacenter_vlan}}

  - name: lifecycle-6.0
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}

      - task: test
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params: &lifecycle-6-params
          BOSH_VSPHERE_VERSION:                                 {{lifecycle_vsphere_6_0_version}}
          BOSH_VSPHERE_CPI_HOST:                                {{lifecycle_vsphere_6_0_host}}
          BOSH_VSPHERE_CPI_USER:                                {{lifecycle_vsphere_6_0_user}}
          BOSH_VSPHERE_CPI_PASSWORD:                            {{lifecycle_vsphere_6_0_password}}
          BOSH_VSPHERE_VLAN:                                    {{lifecycle_vsphere_6_0_vlan}}
          BOSH_VSPHERE_CPI_DATACENTER:                          {{lifecycle_vsphere_6_0_datacenter}}
          BOSH_VSPHERE_CPI_CLUSTER:                             {{lifecycle_vsphere_6_0_first_cluster}}
          BOSH_VSPHERE_CPI_DATASTORE_PATTERN:                   {{lifecycle_vsphere_6_0_datastore_pattern_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_PERSISTENT_DATASTORE_PATTERN:        {{lifecycle_vsphere_6_0_persistent_datastore_pattern_available_to_all_clusters}}
          BOSH_VSPHERE_CPI_SECOND_DATASTORE:                    {{lifecycle_vsphere_6_0_second_datastore_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_LOCAL_DATASTORE_PATTERN:             {{lifecycle_vsphere_6_0_local_datastore_pattern_available_to_a_single_host_in_first_cluster}}
          BOSH_VSPHERE_CPI_RESOURCE_POOL:                       {{lifecycle_vsphere_6_0_first_cluster_first_resource_pool}}
          BOSH_VSPHERE_CPI_SECOND_RESOURCE_POOL:                {{lifecycle_vsphere_6_0_first_cluster_second_resource_pool}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER:                      {{lifecycle_vsphere_6_0_second_cluster}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_DATASTORE:            {{lifecycle_vsphere_6_0_datastore_pattern_available_to_all_hosts_in_second_cluster}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_RESOURCE_POOL:        {{lifecycle_vsphere_6_0_second_cluster_first_resource_pool}}
          BOSH_VSPHERE_CPI_VM_FOLDER:                           {{lifecycle_vsphere_6_0_vm_folder}}
          BOSH_VSPHERE_CPI_TEMPLATE_FOLDER:                     {{lifecycle_vsphere_6_0_template_folder}}
          BOSH_VSPHERE_CPI_DISK_PATH:                           {{lifecycle_vsphere_6_0_disk_path}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER:                   {{lifecycle_vsphere_6_0_nested_datacenter}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_DATASTORE_PATTERN: {{lifecycle_vsphere_6_0_nested_datacenter_datastore_pattern}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_CLUSTER:           {{lifecycle_vsphere_6_0_nested_datacenter_cluster}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_RESOURCE_POOL:     {{lifecycle_vsphere_6_0_nested_datacenter_resource_pool}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_VLAN:              {{lifecycle_vsphere_6_0_nested_datacenter_vlan}}

  - name: lifecycle-6.0-vsan
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}

      - task: test
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          <<: *lifecycle-6-params
          BOSH_VSPHERE_CPI_DATASTORE_PATTERN:                   {{lifecycle_vsphere_6_0_vsan_datastore_pattern_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_DATASTORE:            {{lifecycle_vsphere_6_0_vsan_datastore_pattern_available_to_all_hosts_in_second_cluster}}

  - name: promote-candidate
    serial: true
    plan:
    - aggregate:
      - {trigger: false, passed: [lifecycle-5.1, lifecycle-6.0, lifecycle-6.0-vsan], get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]}
      - {trigger: false, passed: [lifecycle-5.1, lifecycle-6.0, lifecycle-6.0-vsan], get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
      - {trigger: false, get: release-version-semver, params: {bump: major}, tags: ["vsphere-v5.1"]}

    - task: promote
      tags: ["vsphere-v5.1"]
      file: bosh-cpi-src/ci/tasks/promote-candidate.yml
      params:
        aws_access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
        aws_secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

    - put: bosh-cpi-src-out
      tags: ["vsphere-v5.1"]
      params: {repository: updated-repo/, rebase: true, tag_prefix: "v", tag: integer-version/tag-file}

    - put: release-version-semver
      tags: ["vsphere-v5.1"]
      params: {file: release-version-semver/number}

resources:
  - name: bosh-cpi-artifacts
    type: s3
    source:
      regexp:            bosh-vsphere-cpi\.tgz
      bucket:            {{s3_vsphere_cpi_bucket}}
      region_name:       us-east-1
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

  - &bosh-cpi-src-resource
    name: bosh-cpi-src
    type: git
    source:
      uri:         git@github.com:cloudfoundry-incubator/bosh-vsphere-cpi-release.git
      branch:      master
      private_key: {{github_deployment_key__bosh-vsphere-cpi-release}}

  - <<: *bosh-cpi-src-resource
    name: bosh-cpi-src-out

  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

  - name: vsphere-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: vsphere-centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-centos-7-go_agent
