---
groups:
  - name: bosh-vsphere-cpi
    jobs:
      - cache-stemcells
      - build-candidate
      - lifecycle-5.1
      - lifecycle-6.0
      - lifecycle-6.0-vsan
      - bats
      - promote-candidate

jobs:
  - name: cache-stemcells
    plan:
      - aggregate:
        - {trigger: true, get: vsphere-centos-stemcell, tags: ["vsphere-v5.1"]}
        - {trigger: true, get: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}

      - task: setup-container
        tags: ["vsphere-v5.1"]
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: boshcpi/vsphere-cpi-release}
          inputs:
            - name: vsphere-centos-stemcell
            - name: vsphere-ubuntu-stemcell
          run:
            path: echo
            args: ["Finished setting up container."]

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: true, get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false, get: version-semver, params: {bump: patch}, tags: ["vsphere-v5.1"]}

      - put: version-semver
        tags: ["vsphere-v5.1"]
        params: {file: version-semver/number}

      - task: build
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/build-candidate.yml

      - put: bosh-cpi-artifacts
        tags: ["vsphere-v5.1"]
        params: {from: dev-artifacts/.*\.tgz}

  - name: lifecycle-5.1
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}

      - task: test
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          RSPEC_FLAGS:                                          "--tag ~host_local --tag ~vsan_datastore --tag ~nsx --tag ~drs" # fiveone env doesn't support all features the CPI supports
          BOSH_VSPHERE_VERSION:                                 {{lifecycle_vsphere_5_1_version}}
          BOSH_VSPHERE_CPI_HOST:                                {{lifecycle_vsphere_5_1_host}}
          BOSH_VSPHERE_CPI_USER:                                {{lifecycle_vsphere_5_1_user}}
          BOSH_VSPHERE_CPI_PASSWORD:                            {{lifecycle_vsphere_5_1_password}}
          BOSH_VSPHERE_VLAN:                                    {{lifecycle_vsphere_5_1_vlan}}
          BOSH_VSPHERE_CPI_DATACENTER:                          {{lifecycle_vsphere_5_1_datacenter}}
          BOSH_VSPHERE_CPI_CLUSTER:                             {{lifecycle_vsphere_5_1_first_cluster}}
          BOSH_VSPHERE_CPI_DATASTORE_PATTERN:                   {{lifecycle_vsphere_5_1_datastore_pattern_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_INACTIVE_DATASTORE_PATTERN:          {{lifecycle_vsphere_5_1_inactive_datastore_pattern}}
          BOSH_VSPHERE_CPI_SECOND_DATASTORE:                    {{lifecycle_vsphere_5_1_second_datastore_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_RESOURCE_POOL:                       {{lifecycle_vsphere_5_1_first_cluster_first_resource_pool}}
          BOSH_VSPHERE_CPI_SECOND_RESOURCE_POOL:                {{lifecycle_vsphere_5_1_first_cluster_second_resource_pool}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER:                      {{lifecycle_vsphere_5_1_second_cluster}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_DATASTORE:            {{lifecycle_vsphere_5_1_datastore_pattern_available_to_all_hosts_in_second_cluster}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_RESOURCE_POOL:        {{lifecycle_vsphere_5_1_second_cluster_first_resource_pool}}
          BOSH_VSPHERE_CPI_VM_FOLDER:                           {{lifecycle_vsphere_5_1_vm_folder}}
          BOSH_VSPHERE_CPI_TEMPLATE_FOLDER:                     {{lifecycle_vsphere_5_1_template_folder}}
          BOSH_VSPHERE_CPI_DISK_PATH:                           {{lifecycle_vsphere_5_1_disk_path}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER:                   {{lifecycle_vsphere_5_1_nested_datacenter}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_DATASTORE_PATTERN: {{lifecycle_vsphere_5_1_nested_datacenter_datastore_pattern}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_CLUSTER:           {{lifecycle_vsphere_5_1_nested_datacenter_cluster}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_RESOURCE_POOL:     {{lifecycle_vsphere_5_1_nested_datacenter_resource_pool}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_VLAN:              {{lifecycle_vsphere_5_1_nested_datacenter_vlan}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_NESTED_VLAN:       {{lifecycle_vsphere_5_1_nested_datacenter_nested_vlan}}
          BOSH_VSPHERE_CPI_PORTGROUP_STANDARD:                  {{lifecycle_vsphere_5_1_portgroup_standard}}
          BOSH_VSPHERE_CPI_PORTGROUP_DISTRIBUTED:               {{lifecycle_vsphere_5_1_portgroup_distributed}}
          BOSH_VSPHERE_CPI_PORTGROUP_AMBIGUOUS:                 {{lifecycle_vsphere_5_1_portgroup_ambiguous}}
          BOSH_VSPHERE_CPI_PORTGROUP_AMBIGUOUS_RAISE_ISSUE:     {{lifecycle_vsphere_5_1_portgroup_raise_ambiguous_issue}}
          BOSH_VSPHERE_CPI_PORTGROUP_FOLDER_STANDARD:           {{lifecycle_vsphere_5_1_portgroup_folder_standard}}
          BOSH_VSPHERE_CPI_PORTGROUP_FOLDER_DISTRIBUTED:        {{lifecycle_vsphere_5_1_portgroup_folder_distributed}}
          BOSH_VSPHERE_CPI_PORTGROUP_FOLDER_AMBIGUOUS:          {{lifecycle_vsphere_5_1_portgroup_folder_ambiguous}}

  - name: lifecycle-6.0
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}

      - task: test
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params: &lifecycle-6-params
          RSPEC_FLAGS:                                          "--tag ~vsan_datastore"
          BOSH_VSPHERE_VERSION:                                 {{lifecycle_vsphere_6_0_version}}
          BOSH_VSPHERE_CPI_HOST:                                {{lifecycle_vsphere_6_0_host}}
          BOSH_VSPHERE_CPI_USER:                                {{lifecycle_vsphere_6_0_user}}
          BOSH_VSPHERE_CPI_PASSWORD:                            {{lifecycle_vsphere_6_0_password}}
          BOSH_VSPHERE_VLAN:                                    {{lifecycle_vsphere_6_0_vlan}}
          BOSH_VSPHERE_CPI_DATACENTER:                          {{lifecycle_vsphere_6_0_datacenter}}
          BOSH_VSPHERE_CPI_CLUSTER:                             {{lifecycle_vsphere_6_0_first_cluster}}
          BOSH_VSPHERE_CPI_DATASTORE_PATTERN:                   {{lifecycle_vsphere_6_0_datastore_pattern_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_INACTIVE_DATASTORE_PATTERN:          {{lifecycle_vsphere_6_0_inactive_datastore_pattern}}
          BOSH_VSPHERE_CPI_SECOND_DATASTORE:                    {{lifecycle_vsphere_6_0_second_datastore_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_SINGLE_LOCAL_DATASTORE_PATTERN:      {{lifecycle_vsphere_6_0_local_datastore_pattern_available_to_a_single_host_in_first_cluster}}
          BOSH_VSPHERE_CPI_MULTI_LOCAL_DATASTORE_PATTERN:       {{lifecycle_vsphere_6_0_local_datastore_pattern_available_to_multiple_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_RESOURCE_POOL:                       {{lifecycle_vsphere_6_0_first_cluster_first_resource_pool}}
          BOSH_VSPHERE_CPI_SECOND_RESOURCE_POOL:                {{lifecycle_vsphere_6_0_first_cluster_second_resource_pool}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER:                      {{lifecycle_vsphere_6_0_second_cluster}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_DATASTORE:            {{lifecycle_vsphere_6_0_datastore_pattern_available_to_all_hosts_in_second_cluster}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_LOCAL_DATASTORE:      {{lifecycle_vsphere_6_0_second_cluster_local_datastore}}
          BOSH_VSPHERE_CPI_SECOND_CLUSTER_RESOURCE_POOL:        {{lifecycle_vsphere_6_0_second_cluster_first_resource_pool}}
          BOSH_VSPHERE_CPI_VM_FOLDER:                           {{lifecycle_vsphere_6_0_vm_folder}}
          BOSH_VSPHERE_CPI_TEMPLATE_FOLDER:                     {{lifecycle_vsphere_6_0_template_folder}}
          BOSH_VSPHERE_CPI_DISK_PATH:                           {{lifecycle_vsphere_6_0_disk_path}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER:                   {{lifecycle_vsphere_6_0_nested_datacenter}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_DATASTORE_PATTERN: {{lifecycle_vsphere_6_0_nested_datacenter_datastore_pattern}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_CLUSTER:           {{lifecycle_vsphere_6_0_nested_datacenter_cluster}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_RESOURCE_POOL:     {{lifecycle_vsphere_6_0_nested_datacenter_resource_pool}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_VLAN:              {{lifecycle_vsphere_6_0_nested_datacenter_vlan}}
          BOSH_VSPHERE_CPI_NESTED_DATACENTER_NESTED_VLAN:       {{lifecycle_vsphere_6_0_nested_datacenter_nested_vlan}}
          BOSH_VSPHERE_CPI_PORTGROUP_STANDARD:                  {{lifecycle_vsphere_6_0_portgroup_standard}}
          BOSH_VSPHERE_CPI_PORTGROUP_DISTRIBUTED:               {{lifecycle_vsphere_6_0_portgroup_distributed}}
          BOSH_VSPHERE_CPI_PORTGROUP_AMBIGUOUS:                 {{lifecycle_vsphere_6_0_portgroup_ambiguous}}
          BOSH_VSPHERE_CPI_PORTGROUP_AMBIGUOUS_RAISE_ISSUE:     {{lifecycle_vsphere_6_0_portgroup_raise_ambiguous_issue}}
          BOSH_VSPHERE_CPI_PORTGROUP_FOLDER_STANDARD:           {{lifecycle_vsphere_6_0_portgroup_folder_standard}}
          BOSH_VSPHERE_CPI_PORTGROUP_FOLDER_DISTRIBUTED:        {{lifecycle_vsphere_6_0_portgroup_folder_distributed}}
          BOSH_VSPHERE_CPI_PORTGROUP_FOLDER_AMBIGUOUS:          {{lifecycle_vsphere_6_0_portgroup_folder_ambiguous}}
          BOSH_VSPHERE_CPI_NSX_ADDRESS:                         {{lifecycle_vsphere_6_0_nsx_address}}
          BOSH_VSPHERE_CPI_NSX_USER:                            {{lifecycle_vsphere_6_0_nsx_user}}
          BOSH_VSPHERE_CPI_NSX_PASSWORD:                        {{lifecycle_vsphere_6_0_nsx_password}}
          BOSH_VSPHERE_CPI_NSX_CA_CERT:                         {{lifecycle_vsphere_6_0_nsx_ca_cert}}
          BOSH_VSPHERE_CPI_NSX_LB_NAME:                         {{lifecycle_vsphere_6_0_nsx_lb_name}}
          BOSH_VSPHERE_CPI_NSX_POOL_NAME:                       {{lifecycle_vsphere_6_0_nsx_pool_name}}

  - name: lifecycle-6.0-vsan
    plan:
      - aggregate:
        - {trigger: true,  passed: [build-candidate], get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]} # used for job chaining only not for tasks
        - {trigger: false, passed: [build-candidate], get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
        - {trigger: false,                            get: stemcell, resource: vsphere-ubuntu-stemcell, tags: ["vsphere-v5.1"]}

      - task: test
        tags: ["vsphere-v5.1"]
        file: bosh-cpi-src/ci/tasks/run-lifecycle.yml
        params:
          RSPEC_FLAGS:                                          "--tag vsan_datastore"
          BOSH_VSPHERE_VERSION:                                 {{lifecycle_vsphere_6_0_vsan_version}}
          BOSH_VSPHERE_CPI_HOST:                                {{lifecycle_vsphere_6_0_vsan_host}}
          BOSH_VSPHERE_CPI_USER:                                {{lifecycle_vsphere_6_0_vsan_user}}
          BOSH_VSPHERE_CPI_PASSWORD:                            {{lifecycle_vsphere_6_0_vsan_password}}
          BOSH_VSPHERE_VLAN:                                    {{lifecycle_vsphere_6_0_vsan_vlan}}
          BOSH_VSPHERE_CPI_DATACENTER:                          {{lifecycle_vsphere_6_0_vsan_datacenter}}
          BOSH_VSPHERE_CPI_CLUSTER:                             {{lifecycle_vsphere_6_0_vsan_first_cluster}}
          BOSH_VSPHERE_CPI_VM_FOLDER:                           {{lifecycle_vsphere_6_0_vsan_vm_folder}}
          BOSH_VSPHERE_CPI_TEMPLATE_FOLDER:                     {{lifecycle_vsphere_6_0_vsan_template_folder}}
          BOSH_VSPHERE_CPI_DISK_PATH:                           {{lifecycle_vsphere_6_0_vsan_disk_path}}
          BOSH_VSPHERE_CPI_VSAN_DATASTORE_PATTERN:              {{lifecycle_vsphere_6_0_vsan_datastore_pattern_available_to_all_hosts_in_first_cluster}}
          BOSH_VSPHERE_CPI_DATASTORE_PATTERN:                   {{lifecycle_vsphere_6_0_vsan_non_vsan_datastore_pattern_available_to_all_hosts_in_first_cluster}}

  - name: bats
    serial: true
    plan:
      - aggregate:
        - {get: cpi-release,  tags: [vsphere-v5.1], trigger: true,  resource: bosh-cpi-artifacts, passed: [build-candidate]}
        - {get: bosh-release, tags: [vsphere-v5.1], trigger: false, resource: old-bosh-release}
        - {get: stemcell,     tags: [vsphere-v5.1], trigger: false, resource: old-stemcell}
        - {get: pipelines,    tags: [vsphere-v5.1], trigger: false, resource: certification}
        - {get: bosh-cli,     tags: [vsphere-v5.1], trigger: false}
        - {get: bats,         tags: [vsphere-v5.1], trigger: false}
        # Passthrough
        - {get: bosh-cpi-src, tags: [vsphere-v5.1], trigger: false, passed: [build-candidate]}

      - {put: environment, tags: [vsphere-v5.1], params: {acquire: true}}

      - task: prepare-director
        tags: [vsphere-v5.1]
        file: pipelines/vsphere/tasks/prepare-director.yml
        params:
          BOSH_CLIENT:                            {{BOSH_CLIENT}}
          BOSH_CLIENT_SECRET:                     {{BOSH_CLIENT_SECRET}}
          BOSH_VSPHERE_VCENTER:                   {{VCENTER_IP}}
          BOSH_VSPHERE_VCENTER_USER:              {{VCENTER_USER}}
          BOSH_VSPHERE_VCENTER_PASSWORD:          {{VCENTER_PASSWORD}}
          BOSH_VSPHERE_VERSION:                   {{VSPHERE_VERSION}}
          BOSH_VSPHERE_VCENTER_DC:                {{VCENTER_DC}}
          BOSH_VSPHERE_VCENTER_CLUSTER:           {{VCENTER_CLUSTER}}
          BOSH_VSPHERE_VCENTER_DATASTORE:         {{VCENTER_DATASTORE}}
          BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}
          BOSH_VSPHERE_VCENTER_VM_FOLDER:         {{VCENTER_VM_FOLDER}}
          BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER:   {{VCENTER_TEMPLATE_FOLDER}}
          BOSH_VSPHERE_VCENTER_DISK_PATH:         {{VCENTER_DISK_PATH}}
          SSLIP_IO_KEY:                           {{sslip_io_key}}
          USE_REDIS:                              true

      - do:
          - task: deploy-director
            tags: [vsphere-v5.1]
            file: pipelines/shared/tasks/deploy-director.yml

          - task: prepare-bats
            tags: [vsphere-v5.1]
            file: pipelines/vsphere/tasks/prepare-bats.yml
            params:
              BAT_VCAP_PASSWORD:      {{BAT_VCAP_PASSWORD}}
              BOSH_CLIENT:            {{BOSH_CLIENT}}
              BOSH_CLIENT_SECRET:     {{BOSH_CLIENT_SECRET}}
              STEMCELL_NAME:          bosh-vsphere-esxi-ubuntu-trusty-go_agent

          - task: run-bats
            tags: [vsphere-v5.1]
            file: pipelines/shared/tasks/run-bats.yml

        ensure:
          do:
            - task: teardown
              tags: [vsphere-v5.1]
              file: pipelines/shared/tasks/teardown.yml

            - {put: environment, tags: [vsphere-v5.1], params: {release: environment}}

  - name: promote-candidate
    serial: true
    plan:
    - aggregate:
      # temporarily remove VSAN passed constraint as environment is having issues
      - {trigger: false, passed: [lifecycle-5.1, lifecycle-6.0, lifecycle-6.0-vsan, bats], get: bosh-cpi-artifacts, tags: ["vsphere-v5.1"]}
      - {trigger: false, passed: [lifecycle-5.1, lifecycle-6.0, lifecycle-6.0-vsan, bats], get: bosh-cpi-src, tags: ["vsphere-v5.1"]}
      - {trigger: false, get: release-version-semver, params: {bump: major}, tags: ["vsphere-v5.1"]}

    - task: promote
      tags: ["vsphere-v5.1"]
      file: bosh-cpi-src/ci/tasks/promote-candidate.yml
      params:
        AWS_ACCESS_KEY_ID:     {{s3_vsphere_cpi_blobwriter_access_key}}
        AWS_SECRET_ACCESS_KEY: {{s3_vsphere_cpi_blobwriter_secret_key}}

    - put: bosh-cpi-src-out
      tags: ["vsphere-v5.1"]
      params: {repository: updated-repo/, rebase: true, tag_prefix: "v", tag: integer-version/tag-file}

    - put: release-version-semver
      tags: ["vsphere-v5.1"]
      params: {file: release-version-semver/number}

resources:
  - name: bosh-cpi-artifacts
    type: s3
    source:
      regexp:            bosh-vsphere-cpi-([\d\.]+)\.tgz
      bucket:            {{s3_vsphere_cpi_bucket}}
      region_name:       us-east-1
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

  - &bosh-cpi-src-resource
    name: bosh-cpi-src
    type: git
    source:
      uri:         git@github.com:cloudfoundry-incubator/bosh-vsphere-cpi-release.git
      branch:      master
      private_key: {{github_deployment_key__bosh-vsphere-cpi-release}}

  - <<: *bosh-cpi-src-resource
    name: bosh-cpi-src-out

  - name: version-semver
    type: semver
    source:
      key:               current-version
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_vsphere_cpi_bucket}}
      access_key_id:     {{s3_vsphere_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vsphere_cpi_blobwriter_secret_key}}

  - name: vsphere-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: vsphere-centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-centos-7-go_agent

  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1

  - name: certification
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master

    # upgrade resources
  - name: old-bosh-release
    type: s3
    source:
      bucket: bosh-cpi-certification-fixtures
      regexp: precompiled-bosh-(255.8)-on-ubuntu-3232.3.tgz
      region_name: us-east-1

  - name: old-stemcell
    type: s3
    source:
      bucket: bosh-cpi-certification-fixtures
      regexp: bosh-stemcell-(3232.3)-vsphere-esxi-ubuntu-trusty-go_agent.tgz
      region_name: us-east-1

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: environment
    type: pool
    source:
      pool: vsphere-5.1
      uri: git@github.com:cloudfoundry/bosh-cpi-environments.git
      branch: master
      private_key: {{github_deployment_key__bosh-cpi-environments}}
